# Generated by Django 3.1.14 on 2022-07-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('todo', models.CharField(max_length=255)),
                ('isDone', models.BooleanField(default=False)),
            ],
        ),
    ]
