# Generated by Django 4.0.5 on 2022-06-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('todo', models.CharField(max_length=255)),
                ('isDone', models.BooleanField(default=False)),
            ],
        ),
    ]
